MFU-578: add xattr.h header to mfu_io.c
hpc/mpifileutils pull request #582
Opened 2024-08-22 13:00 UTC by Michael-Hennecke

include the xattr.h header in mfu_io.c to avoid compilation errors (ISO C99 and later do not support implicit function declarations)

2024-08-22 14:25 UTC, daltonbohning requested changes
If we do this I think it still needs to be behind the xattr compile flag.

E.g.
https://github.com/hpc/mpifileutils/blob/0a4c530bca5dc2476418a3833a15ab812d636e78/src/common/mfu_flist_archive.c#L35-L37

Then, the real fix to your #578 is to also wrap the uses of the xattr functions.
A workaround is to just build with `-DENABLE_XATTRS=ON`

2024-11-14 21:35 UTC, ofaaland commented
@Michael-Hennecke @daltonbohning can we close this since #583 was merged, which added the `#include <sys/xattr.h>` to mfu_io.c?

2024-11-14 21:49 UTC, daltonbohning commented
> @Michael-Hennecke @daltonbohning can we close this since #583 was merged, which added the `#include <sys/xattr.h>` to mfu_io.c?

Yep, thanks!

2024-11-14 21:50 UTC, daltonbohning commented
@Michael-Hennecke You should just be able to build `main` now with no additional patches

2024-11-14 21:50 UTC, closed without merging