dsync/dcmp: support symlinks targets changes
hpc/mpifileutils pull request #618
Opened 2024-12-20 14:42 UTC by rezib

Update `dsync` and `dcmp` to detect a symlinks targets changes. In this case, the symlinks are reported to be different by `dcmp` and are updated by `dsync`.

Note this works for `dsync` both with or without `c, --contents`.

New function `mfu_compare_symlinks()` is introduced in library API to factorize the logic for all commands.

## Method

In order to reproduce the bug and validate the patch, I wrote this little script `symlink.sh`:

```sh
#!/bin/sh

# Prepare test environment
DATA_DIR=../data

# Remove previous data if existing
if [ -d ${DATA_DIR}/from ]; then
	rm -r ${DATA_DIR}/from
fi
if [ -d ${DATA_DIR}/to ]; then
	rm -r ${DATA_DIR}/to
fi

echo "→ Initialiazing testing data"
mkdir ${DATA_DIR}/from
echo foo > ${DATA_DIR}/from/file1
echo bar > ${DATA_DIR}/from/file2
ln -s file1 ${DATA_DIR}/from/link1
ln -s file2 ${DATA_DIR}/from/link2

echo
echo "→ Launching first dsync"
mpirun -N 2 ${HOME}/bin/dsync ${DATA_DIR}/from ${DATA_DIR}/to

# Change one symlink target
rm ${DATA_DIR}/from/link2
ln -s file1 ${DATA_DIR}/from/link2

echo
echo "→ Launching first dcmp"
mpirun -N 2 ${HOME}/bin/dcmp ${DATA_DIR}/from ${DATA_DIR}/to

echo
echo "→ Launching second dsync"
mpirun -N 2 ${HOME}/bin/dsync ${DATA_DIR}/from ${DATA_DIR}/to

echo
echo "→ Launching second dcmp"
mpirun -N 2 ${HOME}/bin/dcmp ${DATA_DIR}/from ${DATA_DIR}/to
```

## Before

Script output:

```console
$ sh symlink.sh 
→ Initialiazing testing data

→ Launching first dsync
[2024-12-20T08:36:36] Walking source path
[2024-12-20T08:36:36] Walking /home/remi/git/data/from
[2024-12-20T08:36:36] Walked 5 items in 0.001 secs (4545.934 items/sec) ...
[2024-12-20T08:36:36] Walked 5 items in 0.001 seconds (4353.793 items/sec)
[2024-12-20T08:36:36] Walking destination path
[2024-12-20T08:36:36] Walking /home/remi/git/data/to
[2024-12-20T08:36:36] [0] [/home/remi/git/mpifileutils/src/common/mfu_flist_walk.c:516] ERROR: Failed to stat: '/home/remi/git/data/to' (errno=2 No such file or directory)
[2024-12-20T08:36:36] Walked 0 items in 0.001 secs (0.000 items/sec) ...
[2024-12-20T08:36:36] Walked 0 items in 0.001 seconds (0.000 items/sec)
[2024-12-20T08:36:36] Started   : Dec-20-2024, 08:36:36
[2024-12-20T08:36:36] Completed : Dec-20-2024, 08:36:36
[2024-12-20T08:36:36] Seconds   : 0.000
[2024-12-20T08:36:36] Items     : 0
[2024-12-20T08:36:36] Item Rate : 0 items in 0.000295 seconds (0.000000 items/sec)
[2024-12-20T08:36:36] Copying items to destination
[2024-12-20T08:36:36] Copying to /home/remi/git/data/to
[2024-12-20T08:36:36] Items: 5
[2024-12-20T08:36:36]   Directories: 1
[2024-12-20T08:36:36]   Files: 2
[2024-12-20T08:36:36]   Links: 2
[2024-12-20T08:36:36] Data: 8.000 B (4.000 B per file)
[2024-12-20T08:36:36] Creating 1 directories
[2024-12-20T08:36:36] Creating 4 files.
[2024-12-20T08:36:36] Copying data.
[2024-12-20T08:36:36] Copy data: 8.000 B (8 bytes)
[2024-12-20T08:36:36] Copy rate: 693.124 B/s (8 bytes in 0.012 seconds)
[2024-12-20T08:36:36] Syncing data to disk.
[2024-12-20T08:36:36] Sync completed in 0.011 seconds.
[2024-12-20T08:36:36] Setting ownership, permissions, and timestamps.
[2024-12-20T08:36:36] Updated 5 items in 0.000 seconds (25281.382 items/sec)
[2024-12-20T08:36:36] Syncing directory updates to disk.
[2024-12-20T08:36:36] Sync completed in 0.002 seconds.
[2024-12-20T08:36:36] Started: Dec-20-2024,08:36:36
[2024-12-20T08:36:36] Completed: Dec-20-2024,08:36:36
[2024-12-20T08:36:36] Seconds: 0.024
[2024-12-20T08:36:36] Items: 5
[2024-12-20T08:36:36]   Directories: 1
[2024-12-20T08:36:36]   Files: 2
[2024-12-20T08:36:36]   Links: 2
[2024-12-20T08:36:36] Data: 8.000 B (8 bytes)
[2024-12-20T08:36:36] Rate: 326.574 B/s (008 bytes in 0.024 seconds)
[2024-12-20T08:36:36] Updating timestamps on newly copied files
[2024-12-20T08:36:36] Completed updating timestamps
[2024-12-20T08:36:36] Completed sync

→ Launching first dcmp
[2024-12-20T08:36:37] Walking source path
[2024-12-20T08:36:37] Walking /home/remi/git/data/from
[2024-12-20T08:36:37] Walked 5 items in 0.001 secs (4468.399 items/sec) ...
[2024-12-20T08:36:37] Walked 5 items in 0.001 seconds (4269.239 items/sec)
[2024-12-20T08:36:37] Walking destination path
[2024-12-20T08:36:37] Walking /home/remi/git/data/to
[2024-12-20T08:36:37] Walked 5 items in 0.001 secs (7051.838 items/sec) ...
[2024-12-20T08:36:37] Walked 5 items in 0.001 seconds (6870.501 items/sec)
[2024-12-20T08:36:37] Comparing items
[2024-12-20T08:36:37] Comparing file contents
[2024-12-20T08:36:37] Started   : Dec-20-2024, 08:36:37
[2024-12-20T08:36:37] Completed : Dec-20-2024, 08:36:37
[2024-12-20T08:36:37] Seconds   : 0.010
[2024-12-20T08:36:37] Items     : 5
[2024-12-20T08:36:37] Item Rate : 5 items in 0.010120 seconds (494.092677 items/sec)
[2024-12-20T08:36:37] Bytes read: 16.000 B (16 bytes)
[2024-12-20T08:36:37] Byte Rate : 1.544 KiB/s (016 bytes in 0.010 seconds)
Number of items that exist in both directories: 5 (Src: 5 Dest: 5)
Number of items that exist only in one directory: 0 (Src: 0 Dest: 0)
Number of items that exist in both directories and have the same type: 5 (Src: 5 Dest: 5)
Number of items that exist in both directories and have different types: 0 (Src: 0 Dest: 0)
Number of items that exist in both directories and have the same content: 5 (Src: 5 Dest: 5)
Number of items that exist in both directories and have different contents: 0 (Src: 0 Dest: 0)

→ Launching second dsync
[2024-12-20T08:36:38] Walking source path
[2024-12-20T08:36:38] Walking /home/remi/git/data/from
[2024-12-20T08:36:38] Walked 5 items in 0.001 secs (6070.945 items/sec) ...
[2024-12-20T08:36:38] Walked 5 items in 0.001 seconds (5802.053 items/sec)
[2024-12-20T08:36:38] Walking destination path
[2024-12-20T08:36:38] Walking /home/remi/git/data/to
[2024-12-20T08:36:38] Walked 5 items in 0.001 secs (9796.104 items/sec) ...
[2024-12-20T08:36:38] Walked 5 items in 0.001 seconds (9540.583 items/sec)
[2024-12-20T08:36:38] Comparing file sizes and modification times of 2 items
[2024-12-20T08:36:38] Started   : Dec-20-2024, 08:36:38
[2024-12-20T08:36:38] Completed : Dec-20-2024, 08:36:38
[2024-12-20T08:36:38] Seconds   : 0.000
[2024-12-20T08:36:38] Items     : 2
[2024-12-20T08:36:38] Item Rate : 2 items in 0.000189 seconds (10564.682267 items/sec)
[2024-12-20T08:36:38] Updating timestamps on newly copied files
[2024-12-20T08:36:38] Completed updating timestamps
[2024-12-20T08:36:38] Completed sync

→ Launching second dcmp
[2024-12-20T08:36:39] Walking source path
[2024-12-20T08:36:39] Walking /home/remi/git/data/from
[2024-12-20T08:36:39] Walked 5 items in 0.002 secs (2566.423 items/sec) ...
[2024-12-20T08:36:39] Walked 5 items in 0.002 seconds (2456.619 items/sec)
[2024-12-20T08:36:39] Walking destination path
[2024-12-20T08:36:39] Walking /home/remi/git/data/to
[2024-12-20T08:36:39] Walked 5 items in 0.001 secs (3797.583 items/sec) ...
[2024-12-20T08:36:39] Walked 5 items in 0.001 seconds (3672.312 items/sec)
[2024-12-20T08:36:39] Comparing items
[2024-12-20T08:36:39] Comparing file contents
[2024-12-20T08:36:39] Started   : Dec-20-2024, 08:36:39
[2024-12-20T08:36:39] Completed : Dec-20-2024, 08:36:39
[2024-12-20T08:36:39] Seconds   : 0.001
[2024-12-20T08:36:39] Items     : 5
[2024-12-20T08:36:39] Item Rate : 5 items in 0.000552 seconds (9062.173762 items/sec)
[2024-12-20T08:36:39] Bytes read: 16.000 B (16 bytes)
[2024-12-20T08:36:39] Byte Rate : 28.319 KiB/s (016 bytes in 0.001 seconds)
Number of items that exist in both directories: 5 (Src: 5 Dest: 5)
Number of items that exist only in one directory: 0 (Src: 0 Dest: 0)
Number of items that exist in both directories and have the same type: 5 (Src: 5 Dest: 5)
Number of items that exist in both directories and have different types: 0 (Src: 0 Dest: 0)
Number of items that exist in both directories and have the same content: 5 (Src: 5 Dest: 5)
Number of items that exist in both directories and have different contents: 0 (Src: 0 Dest: 0)
```

The content in files tree:

```console
$ ls ../data/from/ -lh
total 8,0K
-rw-rw-r-- 1 remi remi 4  [...]

2025-01-07 17:59 UTC, carbonneau1 approved these changes

2025-01-22 17:08 UTC, rezib commented
Is there anything I can do to help you merge this PR?

2025-01-27 21:46 UTC, carbonneau1 approved these changes

2025-01-27 21:49 UTC, carbonneau1 commented
Salut Rémi,
vous devrez soumettre à nouveau votre commit signé.

Eric

2025-01-28 07:52 UTC, rezib commented
Salut Eric,

Oops, I missed that requirement, I just force-pushed the commit signed with my GPG key.

2025-02-04 23:11 UTC, ofaaland reviewed
Thanks for this contribution!

I have a couple of questions about the code. 

Have you done any testing to determine the performance impact of this change?  I agree with the change generally, but if the impact is significant we should warn users in the release notes.

2025-02-04 23:11 UTC, ofaaland commented on src/dsync/dsync.c
> +        if (type == MFU_TYPE_LINK) {
At this point, we have already compared file contents.  If we find the symlinks point to different targets, didn't we compare the wrong contents, and the results of the file comparison results aren't valid?

It seems like we need to do this earlier.

2025-02-06 17:26 UTC, carbonneau1 requested changes

2025-02-06 17:26 UTC, carbonneau1 commented on src/dsync/dsync.c
> +        if (type == MFU_TYPE_LINK) {
IF I understand the dsync_strmap_compare_data function, we build a list of regular file with the chunk size to compare. The symlink are not in the list, only the files with chuck get compared. The first compare loop cannot be used without serious modification.  But I also agree the symlink compare is done in a loop used for a different purpose. It should be done before.  I suggest another loop after the loop for regular files with chunk size.

2025-02-10 10:01 UTC, rezib commented on src/common/mfu_util.c
> + * value if different, -1 on error when reading symlink. */
Ack, I changed the function to return `abs(strcmp())`, the return value is now -1 for error, 0 when equal, >0 when different. Tell me if you think more elaborate logic should be implemented here.

2025-02-10 10:05 UTC, rezib commented on src/dsync/dsync.c
> +        if (type == MFU_TYPE_LINK) {
For dsync, I moved the symlink destination comparison at the upper level in `dsync_strmap_compare()`, similarly to `dcmp_strmap_compare()`. This avoids messing up with the logic in `dsync_strmap_compare_data()`  and `dsync_strmap_compare_lite()` that are specifically designed for regular files. Tell me what you think!

2025-02-10 10:09 UTC, rezib commented on src/dcmp/dcmp.c
> +            if (mfu_compare_symlinks(mfu_flist_file_get_name(src_list, src_index),
For dsync, I now skip the copy of the symlink in `src_cp_list` and `dst_remove_list` in case of error on `readlink()`. At least, I tried to mimic the behavior in case of `read()` error on regular files with `dsync --content`.

2025-02-10 10:14 UTC, rezib commented
Hello Eric, Olaf,

Thank you for this review!

I pushed an update with some changes to address your concerns. Let me know if there is anything wrong left!

> Have you done any testing to determine the performance impact of this change? I agree with the change generally, but if the impact is significant we should warn users in the release notes.

TBH, no I didn't because personally I don't have access to an infrastructure where I can run significant performance tests…

2025-02-10 17:44 UTC, ofaaland approved these changes
LGTM.  Thanks!

2025-02-10 17:46 UTC, ofaaland commented
> > Have you done any testing to determine the performance impact of this change? I agree with the change generally, but if the impact is significant we should warn users in the release notes.
> 
> TBH, no I didn't because personally I don't have access to an infrastructure where I can run significant performance tests…

Eric, please do some brief before/after performance testing.  Thanks!

2025-02-11 18:00 UTC, carbonneau1 commented
I am reviewing the code. If everything is fine, I will run performance test by tomorrow and merge your fix in.

2025-02-11 20:19 UTC, carbonneau1 reviewed
Looks good. I will tests for performance and if everything looks ok I will merge in your feature.

2025-02-11 20:23 UTC, carbonneau1 approved these changes

2025-02-12 19:12 UTC, merged

2025-02-12 19:18 UTC, carbonneau1 commented
I tested both feature and performance. Evrything looked good. It's in.